CREATE SCHEMA IF NOT EXISTS tww_ag6496;

GRANT ALL ON SCHEMA tww_ag6496 TO postgres;

GRANT ALL ON SCHEMA tww_ag6496 TO tww_user;

GRANT USAGE ON SCHEMA tww_ag6496 TO tww_viewer;



ALTER DEFAULT PRIVILEGES IN SCHEMA tww_ag6496
GRANT ALL ON TABLES TO tww_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA tww_ag6496
GRANT SELECT, TRIGGER, REFERENCES ON TABLES TO tww_viewer;

ALTER DEFAULT PRIVILEGES IN SCHEMA tww_ag6496
GRANT ALL ON SEQUENCES TO tww_user;
